name: My First Workflow
on:
  push:
    branches:
    - "master"

jobs:
  print_the_date:
    runs-on: ubuntu-latest

    steps:
    - name: print the date
      run: echo "The current time and date is $(date)"

    - name: print the current branch
      run: echo ${{ github.ref_name }}

  test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{ secrets.OPENWEATHERMAP_API}}

    steps:

    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # https://github.com/marketplace/actions/setup-maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2

    # https://github.com/marketplace/actions/checkout
    - name: Checkout the source
      uses: actions/checkout@v3

    - name: Test run the app on the server
      run: mvn clean test

    # https://github.com/marketplace/actions/deploy-to-heroku
    - name: Deploy on heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API }}
        heroku_app_name: ${{ secrets.HEROKU_APP_YATA }}
        heroku_email:  ${{ secrets.HEROKU_EMAIL }}  # rescigg76@imageperl.com
        branch: ${{ github.ref_name }} # Tell heroku to take releasing branch